name: Auto Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$CPANEL_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan https://srv68.niagahoster.com:2083/ >> ~/.ssh/known_hosts

      - name: Deploy to cPanel
        run: |
          ssh n1577109@https://srv68.niagahoster.com:2083/ 'bash -s' < ./deploy.sh
        env:
          CPANEL_SSH_PRIVATE_KEY: ${{ secrets.CPANEL_SSH_PRIVATE_KEY }}

      - name: Cleanup SSH key
        run: |
          rm ~/.ssh/id_rsa

